### ISSUE TITLE
Long operations seem to timeout - e.g get-alerts.py when there are a lot of alerts

### ISSUE THREAD

**Issue by alagden** [HewlettPackard/python-hpOneView#14]
Could we have a timeout parameter, as it appears to affect quite a lot of operations when we have a substantial oneview estate.

**Comment by alagden** [comment]
Have run the same script again and sometimes it works. Is there any sort of timeout in the connection code when waiting for a response from oneview?

**Comment by troyhebe** [comment]
There is a timeout for some longer operations. Exactly, what calls is the script making and where/how is it failing?
