### ISSUE TITLE
servers object methods depend on /rest/server-hardware returning all servers

### ISSUE THREAD

**Issue by ajmaidak** [HewlettPackard/python-hpOneView#15]
The servers object methods rely on  /rest/server-hardware returning a list of all servers.  Unfortunately my experience with OneView 2.x this isn't the case.

When I issue the following get: /rest/server-hardware?start-0&count=-1 it only returns 32 items.

Reviewing the oneview api doc:
The number of resources to return. A count of -1 requests all the items. __The actual number of items in the response may differ from the requested count if the sum of start and count exceed the total number of items, or if returning the requested number of items would take too long.__

I tested by passing count values >32 and the OneView API returned >32 servers...  So I'm not sure why passing -1 only returns 32.  This behavior is inconsistent. 

None-the-less even if OneView was returning all servers it Looks like the python sdk needs to be enhanced to support when not all servers are returned as the endpoint does not promise to return a complete list.

**Comment by ChrisLynchHP** [comment]
I would suggest that the code be modified to instead of relying on the `start` and `count` parameters in the URL, that you look at the `nextPageUri` and `prevPageUri` properties in the returned object.  Those are the paginated values to key off of in order to properly get all objects from a specific API endpoint that support paginated results.  This is how we handle Paginated Results in the PowerShell library.

**Comment by troyhebe** [comment]
As Chris mentioned the nextPageUri is the proper way to handle this. However, as a bit of a hack, when the API does not honor a count of -1 it does seem to honor a count of 9999999.

**Comment by athanasiouw** [comment]
I believe there is a similar problem with getting all the networks.  If you make a request, you only get the first 32, not the whole list.

**Comment by tiagomtotti** [comment]
@athanasiouw , @ajmaidak I suggest to migrate your code to the newer version of the SDK and use the OneViewClient class. 

You may find the examples for server-hardware on this link https://github.com/HewlettPackard/python-hpOneView/blob/master/examples/server_hardware.py, and for networks on this link: https://github.com/HewlettPackard/python-hpOneView/blob/master/examples/ethernet_networks.py

OneViewClient handles this pagination issue internally.
