### ISSUE TITLE
Example Scripts do not support Active Directory Users

### ISSUE THREAD

**Issue by LeeSolomonson** [HewlettPackard/python-hpOneView#18]
The provided example scripts seem to only work with local user accounts.  I was able to modify the example pythons scripts to work with AD credentials.  Here are the changes (or, at least, my version) to get the scripts to work:

In the main definition, add:
```
    parser.add_argument('-d', dest='domain', required=False,
                        default='Local',
                        help='''
    HP OneView Authorized Login Domain''')

```
Modify the following line:
`credential = {'userName': args.user, 'password': args.passwd}
`
to:
`credential = {'authLoginDomain': args.domain.upper(), 'userName': args.user, 'password': args.passwd}
`

**Comment by troyhebe** [comment]
Hello Lee,

Thanks for the patch! Sorry, it took me so long to get it applied. I was waiting until I had the initial support for the 2.0 API uploaded first. In any case your patch has been applied.

Troy
