### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by herrryan** [HewlettPackard/python-hpOneView#218]
Is there a way to set timeout for requests when using Restful API?

**Comment by tiagomtotti** [comment]
Hi @herrryan, 

If you're using the Python SDK to connect to the REST API, you can specify the timeout as an argument to the create and update methods. The default behavior is to wait until the Task finishes in the OneView Appliance.

For instance, to create a fc network, you can use the following snippet:
`fc_network = oneview_client.fc_networks.create(options)`

If you'd like to set a timeout, you can specify the parameter:
`fc_network = oneview_client.fc_networks.create(options, timeout=500)`

Note that this is just a timeout for the Python client to wait for the task. It won't affect the processing of the task in OneView.

**Comment by herrryan** [comment]
thanks for the feedback. I will definitely try it out.
