### ISSUE TITLE
Future >=0.15.2 Not Found

### ISSUE THREAD

**Issue by peterzhang718** [HewlettPackard/python-hpOneView#237]
Hello,

I tried to install HPE OV library by running:
python setup.py install

I got the following error message:
Couldn't find index page for 'future' (maybe misspelled?0
.....
No local packages or download links found for future>=0.15.2

I checked the https://pypi.python.org/simple/, I didn't see future-0.15.2.

Please help.

**Comment by GustavoHennig** [comment]
Hello, 

I suggest that you do a `pip install future`
The latest version is 0.16.0, as you can see here: https://pypi.python.org/pypi/future

It looks like the link you posted is outdated: https://pypi.python.org/simple/

**Comment by tiagomtotti** [comment]
@peterzhang718, I'm closing this issue. If you still have any trouble regarding this subject, please reopen it.
