### ISSUE TITLE
Python version 2.7.5 not supported with TLS Backports

### ISSUE THREAD

**Issue by DPrince87** [HewlettPackard/python-hpOneView#259]
We run our systems on CentOS7 which uses 2.7.5. This library does not work with this version unless the __init__.py file is changed from:

if PY2:
    if PYTHON_VERSION < (2, 7, 9):

to:

if PY2:
    if PYTHON_VERSION < (2, 7, 5):

RHELs version of 2.7.5 has tls 1.2 back-ported so connections work as expected.

**Comment by tiagomtotti** [comment]
Hi @DPrince87,
Thanks for openning this issue. We'll investigate and add tests with Python 2.7.5 to in our TOX env,
