### ISSUE TITLE
Acknowledgment of Login Message

### ISSUE THREAD

**Issue by herrryan** [HewlettPackard/python-hpOneView#264]
Hi guys,

is there a way of acknowledge the login message with the restful api? It is the ok button when you open the OneView before you login

BR

**Comment by tmiotto** [comment]
Hi @herrryan are you talking about the one time EULA before any login is done? If not, could you provide a screenshot of the message?

**Comment by herrryan** [comment]
Yes, it is that. And I got the following error message when I tried to log in with the oneviewclient. Any hints?
![oneview_eula](https://cloud.githubusercontent.com/assets/815835/24999212/fbfafe92-203c-11e7-8c50-dc48a14f3d02.PNG)

**Comment by herrryan** [comment]
Ok, I found a setting in the security section to disable this acknowledgement.
