### ISSUE TITLE
Server Profile task creation is aborting

### ISSUE THREAD

**Issue by elliottkat** [HewlettPackard/python-hpOneView#277]
I'm trying to create multiple server profiles at once and do not want to wait for each task to complete so I'm adding a timeout of 5 seconds to server_profiles create. However, after the 5 seconds is reached, the task is aborted. This is what I'm reading in the server_profile create usage for the timeout:

timeout: Timeout in seconds. Wait for task completion by default. The timeout does not abort the operation in OneView, just stop waiting for its completion.

but this is what I'm seeing when trying to create a profile with the 5 second timeout:

2017-06-01 06:27:10,110 ERROR    hpOneView    Waited 5 seconds for task to complete, aborting when creating server profile Encl4, bay 10 Compliant Profile KZPKYJ

It looks like the task_monitor __wait_task_completion is aborting the task after the timeout.

Am I reading the timeout usage incorrectly in the server_profile create function?

**Comment by tmiotto** [comment]
Hi @elliottkat 

Nope, you're not reading it wrong, the way it was implemented it waits synchronously for the task to finish, and if it reaches the timeout it aborts waiting for the task, but not send any cancellation signal to OneView.

So you can use a try-except to catch these timeout exceptions and create them assynchronously.

However, it may take some time to the timeout occur for each of them, and you may lost track when the creation is complete. Fortunately you can bypass that using Python threads.

I've created this [code example that may help you to do that](https://gist.github.com/tmiotto/904eb614c40bc6c25d2f9b8a8b06591e).

Thanks for pointing that out!

**Comment by elliottkat** [comment]
Thanks so much, Thiago!
