### ISSUE TITLE
Profile local storage is not working

### ISSUE THREAD

**Issue by danielreed** [HewlettPackard/python-hpOneView#28]
Configuring local storage from define profile isn't working correctly.  It looks like make_LocalStorageEmbeddedController from common does nothing.  Maybe this has not be implemented yet?

**Comment by tkubica12** [comment]
Same here, looks like helper from profile.py to make local storage dictionary has issues due to LocalStorageEmbeddedController from common being empty.

**Comment by danielreed** [comment]
@tkubica12 we've merged a fix for this issue and it should be available now.
