### ISSUE TITLE
The instance of OneViewClient doesn't detect that the session idle time has expired

### ISSUE THREAD

**Issue by stenioaraujo** [HewlettPackard/python-hpOneView#280]
When an instance of OneViewClient is created, a session is created to that instance. We assume that the session is considered valid until there is an explicit call to the method `logout` within the connection class (https://github.com/HewlettPackard/python-hpOneView/blob/master/hpOneView/connection.py#L500). However, after 24 hours (default value for the idle time) the session expired, OneViewClient didn't detect it, which resulted in the exception HPOneViewException with Authorization error.

Is there a way to verify if the session expired using hpOneView?

**Comment by tmiotto** [comment]
Hi @stenioaraujo 

OneView doesn't offer a way to validate the token besides doing a request and getting Unauthorized.

However, you can do open a new login session before your token expires, so you won't get the Unauthorized error.

**Comment by ricardoas** [comment]
Hi @tmiotto!

So our best option here is to create a new client for each bunch of operations instead of reusing (with the possibility of seeing the unauthorized error) the same client. This way, we rely on the fact that this client's token will expire in a day and OneView will do its magic to purge the bad guys eventually...

**Comment by ricardoas** [comment]
We started being worried after seeing a couple of thousands of opened sessions in OneView after a day performing deployments... but maybe this is not the case and we should stop being cautious :)

**Comment by tmiotto** [comment]
Hi @ricardoas!

You can surely drive the requests this way.

As far as I've used OneView to handle the login sessions, I hadn't any problem, besides not stressing it out to the maximum, but I guess this is not your situation also.

If you are still worried about the multiple open sessions you can call the `logout` for each client after using them, so the token will become invalid and the session will be removed from OneView.
