### ISSUE TITLE
Error in Generating RabbitMQ Key Pair on the appliance

### ISSUE THREAD

**Issue by AVerma87** [HewlettPackard/python-hpOneView#3]
Command used for Kay pair generation:
 ./scmb.py -a [HP OneView Appliance IP] -u Administrator -p MyPass -g

Error Reported : From file security.py

Resolution:
I modified the file python-hpOneView/blob/master/hpOneView/security.py
Funtion: def gen_rabbitmq_ca(self)
                    request = {'type': 'RabbitMqClientCert', 'commonName': 'default'}

I replaced new value to type key: RabbitMqClientCertV2 and the generation of key pair was successful.

**Comment by troyhebe** [comment]
Excellent, thanks for the patch! Right now we are still chasing the upstream API train and are still behind. I just pushed the change.

**Comment by AVerma87** [comment]
Thanks Troy.
