### ISSUE TITLE
Must set API version 500 in order to see OS Deployment Plan in Synergy template

### ISSUE THREAD

**Issue by kmullican** [HewlettPackard/python-hpOneView#306]
### Scenario/Intent
I have a Synergy OneView template with an OS Deployment Plan, but when query the template with oneview_client.server_profile_templates.get_by_name, the OS Deployment Plan is missing from the output.  API version is set to 300 in config.json, per the OneView SDK GitHub README.md.

HPE has informed me that setting API version to 500 fixes the issue (and I have verified that is the case), but this is not clear from the README.md.  So this may be a combination of documentation fix plus code fix to automatically detect highest API version supported?

### Environment Details
 - **OneView SDK Version:** 3.3.0
 - **OneView Appliance Version:**  3.10.04-0299553 
 - **OneView Client API Version:** 300
 - **Python Version:** 3.4.5
 - **Platform:** CentOS 7.3 x86_64

### Steps to Reproduce
Create template with an OS Deployment Plan.  
Read the template in via Python SDK:
oneview_client = OneViewClient.from_json_file('connect.json')
my_template = oneview_client.server_profile_templates.get_by_name('test-template')
pprint(my_template)

### Expected Result
See the complete template, including OS Deployment Plan

### Actual Result
OS Deployment Plan is missing

**Comment by bsoutham** [comment]
Deployment plans are not supported on Server Profile Templates until the 3.10 release (500 API), so you would need to use the 500 API to get the information.
The previous version (OneView 3.0, API 300) The SPT didn't support having a Deployment Plan, only a Server Profile supported them.  So the behavior you are describing is expected and correct.  Deployment plans should only show up on a Server Profile Temple when using the 500 API.

**Comment by kmullican** [comment]
What I'm getting at is that the "OneView 3.0" section of the GitHub README specifically states how to set api_version to 300 for OneView 3.0, but does not mention anything about the new OneView 3.10 and the requirement for setting api_version to 500 (which is required in order to use templates on Synergy).

**Comment by fgbulsoni** [comment]
Hey guys, I've made some updates on the README to clarify this behaviour and explain how to set the API version to the desired one. @kmullican @bsoutham feel free to take a look and share your thoughts on the PR #307

**Comment by kmullican** [comment]
@fgbulsoni thanks, where can I preview the updated README.md?

**Comment by fgbulsoni** [comment]
Should be able to see it [here](https://github.com/HewlettPackard/python-hpOneView/blob/9ccab12842f75ce2a7e32cbc138a415a98b6771b/README.md)

**Comment by kmullican** [comment]
@fgbulsoni this change is very helpful, looks great.  thanks!

**Comment by fgbulsoni** [comment]
#307 is merged now, so this issue should *mostly* be solved. 

We may revisit it to see if we'd like to change/update our default version or behavior, but as that would be a breaking change it is likely something to be done carefully/in the future.

Closing down the issue for now.
