### ISSUE TITLE
Could not find mappings for OneView's Index Resources

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/python-hpOneView#312]
Hi...

### Scenario/Intent
The thing I'm trying to answer here is: given an UUID, does it refers to a server hardware, an enclosure or a rack?

### Environment Details
We're using OneView 3.00.05-0271823 and it seems the search bar queries [this endpoint](http://h17007.www1.hpe.com/docs/enterprise/servers/oneview3.0/cic-api/en/api-docs/current/index.html#rest/index/resources)

I've taken a look at hpOneView and I could not find it... is it already implemented? If not, are there any plans on including this in a near version?

Thanks!

**Comment by fgbulsoni** [comment]
These endpoints are not currently implemented. I'll move them up on the priority list.

**Comment by ricardoas** [comment]
Thanks, @fgbulsoni!
