### ISSUE TITLE
Add utilization to Racks

### ISSUE THREAD

**Issue by danielreed** [HewlettPackard/python-hpOneView#314]
### Scenario/Intent
Retrieve hardware utilization for racks

### Environment Details
 - **OneView SDK Version:** All versions
 - **OneView Appliance Version:** All

**Comment by fgbulsoni** [comment]
> Retrieve hardware utilization for racks

Hello @danielreed , not sure I understand.

Can you point to which endpoint you require? Or which resource are you trying to retrieve utilization from?

Verifying the REST API I haven't seen anything related to "utilization" on the "Rack" resource: http://h17007.www1.hpe.com/docs/enterprise/servers/oneview3.0/cic-api/en/api-docs/current/index.html#rest/racks

**Comment by fgbulsoni** [comment]
Are perhaps any of these what you require?
[Power Devices Get Utilization Example](https://github.com/HewlettPackard/python-hpOneView/blob/8e6bfba45c1f342b135c229071964b12ee359ada/examples/power_devices.py#L96)
[Server Hardware Get Utilization Example](https://github.com/HewlettPackard/python-hpOneView/blob/2e5415862efed569aeb57dc5ba285be6a27b746c/examples/server_hardware.py#L57)
[Enclosures Get Utilization Example](https://github.com/HewlettPackard/python-hpOneView/blob/2e5415862efed569aeb57dc5ba285be6a27b746c/examples/enclosures.py#L123)

**Comment by danielreed** [comment]
I think we can close this issue.  It looks like racks.get_device_topology() will give us what we want.

**Comment by fgbulsoni** [comment]
Awesome @danielreed , closing down the issue in that case.
