### ISSUE TITLE
Feature Request: Support allocator/collector methods in IPv4 ranges.

### ISSUE THREAD

**Issue by dtynan** [HewlettPackard/python-hpOneView#316]
### Scenario/Intent
The HP OneView API supports a primitive IPAM system for allocating IP addresses within the
ranges defined on the appliance.

The API docs show a `PUT /rest/id-pools/ipv4/ranges/{id}/allocator` which will allocate an IP
address from the specified range, and `PUT /rest/id-pools/ipv4/ranges/{id}/collector` to release
it back into the pool.

### Environment Details
 - **OneView SDK Version:** 500 (but this has been there for a while, I think)
 - **OneView Client API Version:** Latest client (head of tree)
 - **Python Version:** Python 2.7.12
 - **Platform:** Ubuntu 16.04.3 LTS

### Steps to Reproduce
No support for the above API methods.

Happy to add the functionality and submit upstream.

**Comment by fgbulsoni** [comment]
Sure @dtynan , those methods/endpoints are indeed not currently supported and could be added. 
Feel free to open a PR to add those in and request my review in it.

**Comment by fgbulsoni** [comment]
After another discussion, it seems these endpoints for the ipv4 ranges are not available in the REST API documentation and should not be supported at this moment.
I'll close down this issue, but it can be reopened if we do want and have the means to support that in the SDK, or if this is contributed.
