### ISSUE TITLE
Is it possible to login with session token?

### ISSUE THREAD

**Issue by ricardoas** [HewlettPackard/python-hpOneView#324]
### Scenario/Intent
I have a RESTful service that queries OneView resources via python-hpOneView and I want to provide session resources in this service using OneView credentials. The simple scenario is, considering each RESTful service corresponds to a single OneView appliance:
* the service knows OneView ip address;
* the user post to the service a username+password combination; it creates a hpOneView client instance and gives back the x-auth-token on the service header
* the user access other services resources passing x-auth-token header **which is used to build another hpOneView client instance and perform requests**.

I know that python-hpOneView POSTs username+password to [OneView's /rest/login-sessions](https://github.com/HewlettPackard/python-hpOneView/blob/master/hpOneView/connection.py#L491) when creating a new client instance and I think that a similar approach can be used with the session token and a [PUT request to validate it](http://h17007.www1.hpe.com/docs/enterprise/servers/oneview3.0/cic-api/en/api-docs/current/index.html#rest/login-sessions). 

Would you consider providing this additional authentication in a near version?

**Comment by fgbulsoni** [comment]
Looks the same as #273 .

Possibly doable, but it's important to mention that the maintainer's role for this SDK is currently being transitioned to another team by end of this month.

I'll try to get this into our list of priorities before the hand over.

**Comment by ricardoas** [comment]
Thank you, @fgbulsoni!

It is indeed the same as #273... sorry for opening a new issue!

**Comment by fgbulsoni** [comment]
Resolved by #335 .
