### ISSUE TITLE
Python-Future link error on README.md

### ISSUE THREAD

**Issue by lets00** [HewlettPackard/python-hpOneView#353]
There is a link error on README.md in the sentence:
```
The HPE OneView Python library depends on the Python-Future library to provide Python 2/3 compatibility. This will be installed automatically if you use the installation methods described below.
```
The link to Python-Future on README.md is http://python-future.org/index.htm, but this link is a 404 page.

The correct link is http://python-future.org/index.html.
=)

**Comment by madhav-bharadwaj** [comment]
Hi @lets00, Thank you for this find. We really appreciate your interest.

We have fixed this issue in the following PR.
https://github.com/HewlettPackard/python-hpOneView/pull/357

Looking forward for many more contributions from you.

Regards,
SDK team,
Hewlett Packard Enterprise.
