### ISSUE TITLE
Bug in index_resources.get_all()

### ISSUE THREAD

**Issue by eamonnotoole** [HewlettPackard/python-hpOneView#364]
### Scenario/Intent
List all resources of a given category (disks in my case) using the Index Service

### Environment Details
 - **OneView SDK Version**:  4.4
 - **OneView Appliance Version:** 3.1
 - **OneView Client API Version:** 500
 - **Python Version:** 2.7
 - **Platform:** Running on Ubuntu

Note that this bug is independent of the Environment, and purely a function of the SDK.

### Steps to Reproduce
Try to list all of the drives on a multi-enclosure Synergy (for example).  You only get the *first* page of results.

### Expected Result
We should get *all* disks

### Actual Result
Only get the first-page of results.

The essential issue is that index_resource.get_all() calls the get method, not the get_all method.  The complication is that index_resource.get_all() builds its own URI complete with filtering.  A proposed fix follows.

**Comment by soodpr** [comment]
HI @eamonnotoole - Trying to understand the issue to review the PR. May i know how you are calling the get_all() present in hpOneView/resources/search/index_resources.py file. Can you give the example here.
Based on my understanding it should give you all resources if you don't set count or start parameter.
