### ISSUE TITLE
Should there be Microsoft Word substitute as epub is not sufficient as substitute ?

### ISSUE THREAD

**Issue by vidushidewan** [HewlettPackard/python-hpOneView#427]
[NewDraftMicrosoftWordSubstitute.txt](https://github.com/HewlettPackard/python-hpOneView/files/3051461/NewDraftMicrosoftWordSubstitute.txt)
### Scenario/Intent
[What you are trying to achieve but can't?]

### Environment Details
 - **OneView SDK Version:** [Version of this SDK for which you are encountering the issue]
 - **OneView Appliance Version:** [Version of the OneView appliance you're interacting with]
 - **OneView Client API Version:** [API version listed in your configuration file or dictionary]
 - **Python Version:** [Version of Python in your environment]
 - **Platform:** [OS distribution and release version]

### Steps to Reproduce
[What are the complete steps needed to do in order to reproduce your problem?]

### Expected Result
[What do you *expect* to happen after taking the steps above?]

### Actual Result
[What *actually* happens after the steps above? Include error output or a link to a gist.]

**Comment by vidushidewan** [comment]
Suggestion  to file an issue at HPEDEV Slack

**Comment by soodpr** [comment]
@vidushidewan - I am not sure what you are suggesting here. We are not using any editor in this library. This library provides a Python interface to the HPE OneView REST APIs. 
If you are facing any issue with the HPE OneView Python sdk, then please elaborate the issue in detail.

**Comment by vidushidewan** [comment]
Sorry Mam,
I didn't get you right maybe.
I am not talking about editor please.
Sorry for misconception.

**Comment by soodpr** [comment]
@vidushidewan - Np. Please elaborate the issue by providing us the error you are getting.

**Comment by vidushidewan** [comment]
No
It was just a suggestion

**Comment by ChrisLynchHPE** [comment]
@vidushidewan This project does not use `epub` document format for any assets.  As @soodpr asked, are you sure you are asking this question to the correct GitHub project?

**Comment by vidushidewan** [comment]
Hello Chris
I am not sure if I wrote on the correct project at GitHub.
But, I wasn't sure which project should be approached for this
As for my books at Divine Publishers, I faced some trouble uploading ebooks
for sale
Later, I realised that the format is wrong , EPUB is the format usually
used for ebooks
And I might be wrong , not sure to say that EPUB is used exclusively by
Kindle
So. Later tried to find about EPUB and realised that it's Microsoft who
makes EPUB format.

That is the reason I tried to add a project to you that it is something I
don't know and it's not approachable to me
Please guide on this as I am not sure still
Can I try to code for type text document with HPE


Thanks
Vidushi Dewan
Proprietor - DAKSH GROUP

**Comment by JohnAZoidberg** [comment]
Please close, this is obviously not related to the OneView library.

**Comment by soodpr** [comment]
closing this issue as this is not related to OneView python sdk.

**Comment by vidushidewan** [comment]
@Daniel,  thanks
May I ask you if any action needs to be taken from my end ?
Since the wrong project was approached earlier ?
