### ISSUE TITLE
Unable to retrieve Server Hardware details  by filter “ServerName” but able to do it through filter “name”

### ISSUE THREAD

**Issue by Imranatnisum** [HewlettPackard/python-hpOneView#434]
### **Scenario/Intent**
Using python-hpOneView/examples/server_hardware.py
to get server hardware details though method 
server_byField=oneview_client.server_hardware.get_by(“filer”, “filterValue”)
WHEN , filer=“ServerName” I am getting empty list.

### **Environment Details**

* **OneView SDK Version: release/4.8.0
* OneView Client API Version: 4.10.01-0348545
* **Python Version: 3.7
* **Platform: macOS

### **Steps to Reproduce**
1. Retrieve a Server hardware details through server_hardwares.get_by(" ServerName”,server_name)

### **Expected Result**
It should return a list with one element

### **Actual Result**
It returns empty list .
But when filter is is “name” instead of “ServerName” it returns a list with one element as expected

**Comment by sijeesh** [comment]
@Imranatnisum, Name and ServerName are different fields and values of those fields are not the same.

As per the API doc, please see the difference,
Name :  
    For blade servers, it is the location-based name of the server, which is formed by concatenating the enclosure name and the bay number. For rack servers, it is the serial number prefixed by word "ILO" e.g. ILOUSE31835LS

ServerName:
     The name of the server as reported by the iLO. The iLO gets this information from a running operating system that has monitoring software installed, like Agentless Management Service.

Are you passing the name field value to filter the resource by ServerName ?

**Comment by Imranatnisum** [comment]
I am passing value of ServerName with filter ServerName..But i am getting empty list .I very well acknowledge that values are different for filters "name" and "ServerName"

**Comment by sijeesh** [comment]
@Imranatnisum , Thanks for the update.

Basically get_by calls get_all method with filter, Please try the below code and update if that working for you.

server_hardware.get_all(filter="ServerName='name of the server'")

**Comment by Imranatnisum** [comment]
@sijeesh , Thank u very much
server_hardware.get_all(filter="ServerName='name of the server'")  works as expected
But , I wonder why  server_byField=oneview_client.server_hardware.get_by(“filer”, “filterValue”) gives empty list!!!

**Comment by sijeesh** [comment]
@Imranatnisum , Need to have a look into this, maybe there is some issue with the encoding of the filter value. will update you soon.
