### ISSUE TITLE
Trying to load config

### ISSUE THREAD

**Issue by bradawk1** [HewlettPackard/python-hpOneView#437]
### Scenario/Intent
Just trying to understand the mechanics of starting to use the python OneView interface.

### Environment Details
 - **OneView SDK Version:** 5.0.0
 - **OneView Appliance Version:** 4.20.01-0380241
 - **OneView Client API Version:** 1000
 - **Python Version:** 2.7.12
 - **Platform:** RHEL 7.6

### Steps to Reproduce
I've downloaded the sdk to ~/python-hpOneView. Not wanting to alter the sdk code, I created my working directory as ~/tasks and a ~/config.json with contents:

```
config = {
  "ip": "1.2.3.4",
  "credentials": {
    "userName": "Administrator",
    "authLoginDomain": "",
    "password": 'mypassword'
  },
  "api_version": 1000,
  "ssl_certificate": "~/oneview.crt"
}

```
I ran python setup.py install --user
I then copied one of the examples over to my tasks directory and edited it. Contents of server_hardware_types.py:

```
import sys
sys.path.append('/home/mysid/python-hpOneView/examples')
from pprint import pprint
from hpOneView.oneview_client import OneViewClient
from config_loader import try_load_from_file
config = try_load_from_file('/home/mysid/config.json')
oneview_client = OnceViewClient(config)
server_hardware_types - oneview_client.server_hardware_types
print("\nGet all server hardware types")
server_hardware_types_all = server_hardware_types.get_all()
pprint(server_hardware_types_all, depth=3)

```

### Expected Result
A listing of the server hardware types

### Actual Result

```
Traceback (most recent call last):
File "server_hardware_types.py", line 9, in 
oneview_client = OneViewClient(config)
File "build/bdist.linux-x86_64/egg/hpOneView/oneview_client.py", line 124, in init
self.__connection = connection(config["ip"], config.get('api_version", self.DEFAULT_API_VERSION), config.get('ssl_certificate', False),
TypeError: string indices must be integers, not unicode

```

If I comment out the config = try_load_from_file line and insert the contents of config.json at that point, then the script runs correctly.  What am I doing wrong?

**Comment by sijeesh** [comment]
@bradawk1,
Problem is in this line -    config = try_load_from_file('/home/mysid/config.json')
Replace that line with this - config = try_load_from_file(filename='/home/mysid/config.json')  

try_load_from_file(config, file_name=None) -  takes one default argument(config) and one keyword argument(file_name).  In your code filapath string  is getting assigned to first argument "config" not to file_path argument.

**Comment by bradawk1** [comment]
Great!  I'll give that a try in the morning.  Thanks!

**Comment by bradawk1** [comment]
Got it working.  I had to make three changes.  First was to my config.json file.  I had to remove the 'config = ' at the beginning of the file.  In the script, if I just try:
`config = try_load_from_file(file_name='/home/mysid/config.json')`
it says,
`TypeError: try_load_from_file() takes at least 1 argument (1 given)`
 Which really doesn't make much sense.  :)
So, I tried,
`try_load_from_file(config,file_name='/home/mysid/config.json')`
It complains:
`NameError: name 'config' is not defined`
So, I added on the line before that:
`config=''`
Then it worked.  Thanks!

**Comment by sijeesh** [comment]
@bradawk1 ,

Sorry I missed it.

In Python , default arguments are mandatory but keyword arguments are not. 
For try_load_from_file method, config is a mandatory argument and file_name is not mandatory as its a keyword argument and its already have a default value. 

It's not mandatory to use try_load_from_file method, it's just an example for loading the configuration.
You can define the config dictionary in the same file and pass that to OnceViewClient as below.

config = {
  "ip": "1.2.3.4",
  "credentials": {
    "userName": "Administrator",
    "authLoginDomain": "",
    "password": 'mypassword'
  },
  "api_version": 1000,
  "ssl_certificate": "~/oneview.crt"
}
oneview_client = OnceViewClient(config)

Let me know if it doesn't work.

**Comment by bradawk1** [comment]
Hi Sijeesh,

Yes, that does work.  It was how I got something working in the first place.  :)
I just didn't want to have to put that in every script.  So, it is good I got the load from file working.  My next step is to figure out how to create a server profile template.  The example given doesn't show much detail about creating a template.  Mostly it shows how to extract.

**Comment by sijeesh** [comment]
Please check the Server profile template example file for more examples.
https://github.com/HewlettPackard/python-hpOneView/blob/release/v4.8.0/examples/server_profile_templates.py

Closing the issue as the problem got solved.
