### ISSUE TITLE
get_by function for id_pools_ipv4_ranges

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/python-hpOneView#439]
### Scenario/Intent
Consistency in python OneView SDK: id_pools_ipv4_ranges should have function get_by like others functions

### Environment Details
 - **OneView SDK Version: 4.8
 - **OneView Appliance Version:4.2
 - **OneView Client API Version:600
 - **Python Version:3.7
 - **Platform: Redhat

### Steps to Reproduce
other function like ethernet_networks , fc_networks have a function called get_by for instance
ethernet_networks.get_by('name', this_name)
id_pools_ipv4_ranges does not support this. Suggest to have consistency in the SDK

### Expected Result
be able to use get_by

### Actual Result
Function not supported when using the syntax get_by

**Comment by sijeesh** [comment]
@DungKHoang , There is another module to get the range details, please refer to the below module.
https://github.com/HewlettPackard/python-hpOneView/blob/release/v4.8.0/hpOneView/resources/servers/id_pools_ranges.py
