### ISSUE TITLE
Identify an  IPv4 range without knowing its URI 

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/python-hpOneView#440]
### Scenario/Intent
Want to find an ipV4_range by name. as the ipv4pools-range does not get a function get_by
When I look at the library the get function is defined as follow
        """
        Gets an IPv4 range by ID or URI.

        Args:
            id_or_uri: Can be either the range ID or URI.

What is the range ID? and how can I find it?
The goal is to identify an IPv4 range without knowing its URI.

### Environment Details
 - **OneView SDK Version:** 4.8
 - **OneView Appliance Version:**4.20
 - **OneView Client API Version:** 500
 - **Python Version:** 3.7
 - **Platform:** RedHat

**Comment by sijeesh** [comment]
@DungKHoang,
Refer the below module to get ranges.
https://github.com/HewlettPackard/python-hpOneView/blob/release/v4.8.0/hpOneView/resources/servers/id_pools_ranges.py
