### ISSUE TITLE
get attributes of JBOD disk in server profiles - Erase on delete and permanent

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/python-hpOneView#442]
### Scenario/Intent
Get attributes 'erase on delete ', 'permanent' of  logicalJBOD in server profile (template)

### Environment Details
 - **OneView SDK Version:**4.80
 - **OneView Appliance Version:** 4.20
 - **OneView Client API Version:** 1000
 - **Python Version:**3.7
 - **Platform:**RedHat

### Steps to Reproduce
Create a profile template with local storage and embedded controller from the GUI
Check 'erase on delete'and 'permanent for the logical disk attributes
Use OneView python and call oneview_client.server_profile_templates.get_by_name(SAS-template)
Check the output JSON file and cannot find attributes on logical disk

### Expected Result
See attributes in JSON file

### Actual Result
No attribute

[SAS-JSON.txt](https://github.com/HewlettPackard/python-hpOneView/files/3384282/SAS-JSON.txt)

**Comment by sijeesh** [comment]
@DungKHoang , Don't compare the fields available in different versions of OneView, it will be different.  I can see these fields are available in API version 500 but not in API version 800.
