### ISSUE TITLE
Where can I get a backup URI to restore devices on oneview ?

### ISSUE THREAD

**Issue by KTEngineer91** [HewlettPackard/python-hpOneView#444]
I am trying to run the example script to restore devices on oneview:

https://github.com/HewlettPackard/python-hpOneView/blob/release/v4.8.0/examples/restores.py

This script says to use a backup uri. Here is the example one given:

uri_of_backup_to_restore = "/rest/backups/example_backup_2017-04-25_195515"

I am currently on oneview now and I'm trying to find a backup uri to use but I do not know how I can get this uri. I am able to create a backup under settings -> backup, but where can I find a uri to use on oneview ? Thank you for your time.

**Comment by DungKHoang** [comment]
Use the oneview_client.backups.get_all() and filter out on the name of your backup to find the uri

**Comment by sijeesh** [comment]
@saturnsbelt703 , as Dung suggested use get_all() to get the current backup URI.
From the API doc: Only a single backup can exist on the appliance at a time - it is overwritten each time a backup is requested.
