### ISSUE TITLE
Authorization error: User not authorized for this operation.

### ISSUE THREAD

**Issue by venkatchidipudi** [HewlettPackard/python-hpOneView#5]
Hi Experts,
I am trying to upgrade oneview appliance through python script and function is "upload_fw()", The file uploading process showing successfully,finally I am getting the exception like  below:
 
Appliance Version : 1.20.05-0201918
Patch file : HP_OneView_1.20.05_upgrade_from_any_previous_version_Z7550-96169.bin
 
Traceback (most recent call last):
  File "hp_nfvsys_upload_fw.py", line 12, in <module>
    upload_details = OneView_Settings.upload_fw("/root/venkat/HP_OneView_1.20.05_upgrade_from_any_previous_version_Z7550-96169.bin","HP_OneView",verbose=True)
  File "/root/venkat/hpOneView/settings.py", line 58, in upload_fw
    raise HPOneViewException(body)
hpOneView.exceptions.HPOneViewException: {'errorCode': 'AUTHORIZATION', 'recommendedActions': ['Please verify your credentials and re-authenticate before attempting the operation again.'], 'data': {}, 'nestedErrors': [], 'message': 'Authorization error: User not authorized for this operation.', 'errorSource': None, 'details': 'User not authorized for this operation.'}
 
Please provide solution...
 
Thanks,
Venkat.

**Comment by troyhebe** [comment]
Hello Venka,

The error coming back from the appliance is: 

   Authorization error: User not authorized for this operation

Which begs the question are you using the appliance local Administrator user to perform the operation or are you using a different account? If you are using a different account can you please run the get-users.py script and provide the output and the account name you are trying to use.

Troy
